disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
  - function_body_length
  - cyclomatic_complexity
  - line_length
  - force_cast
  - type_body_length
  - file_length
  - function_parameter_count
  - force_try
  - array_init
  - notification_center_detachment
  - unused_setter_value
  - type_name
  - large_tuple
  - nesting
opt_in_rules:
  # - unavailable_function //Unavailable Function Violation: Unimplemented functions should be marked as unavailable.
  # - missing_docs //Missing Docs Violation: public declarations should be documented.
  - untyped_error_in_catch
  - yoda_condition
  - empty_string
  - type_name
  - implicit_getter
  - pattern_matching_keywords
  - extension_access_modifier
  - unneeded_parentheses_in_closure_argument
  - number_separator
  - syntactic_sugar
  - first_where
  - closure_spacing
  # - conditional_returns_on_newline //Conditional Returns on Newline Violation: Conditional statements should always return on the next line
  # - convenience_type //Types used for hosting only static members should be implemented as a caseless enum to avoid instantiation.
  # - contains_over_first_not_nil //Contains over first not nil Violation: Prefer `contains` over `first(where:) != nil`
  - weak_delegate
  - empty_count
  # - file_header //File Header Violation: Header comments should be consistent with project patterns.
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing
  # - private_outlet //Private Outlets Violation: IBOutlets should be private to avoid leaking UIKit to higher layers.
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  # - sorted_imports //Sorted Imports Violation: Imports should be sorted. (sorted_imports)
  # - object_literal //Object Literal Violation: Prefer object literals over image and color inits.
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - literal_expression_end_indentation
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - genstrings.swift
  - Localize.swift
#force_cast: warning # implicitly. Give warning only for force casting
identifier_name:
  excluded:
    - id

